language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install numpy --use-mirrors # optional reqs
  - pip install xlrd xlsxwriter openpyxl --use-mirrors # competitors
  - pip install coverage coveralls --use-mirrors # test coverage

# command to run tests
script:
  - nosetests --with-coverage --cover-package=pyexcelerate

after_success:
  - coveralls
